### PR TITLE
select_view: Cache required_size

### PR DESCRIPTION
**Pull request by brianc118**
Cache required size when we know it doesn't need to be recomputed. Cache
is invalidated whenever we take mutable reference to items or mutate
items.

https://github.com/facebookincubator/below has an issue where the UI is
very slow because we have >1000 processes in the process view. This
patch fixes it.

Tested with `cargo test`

### CODE REVIEW

**Comment by gyscos** [comment]
Looks good, thanks for the work!

**Comment by brianc118** [comment]
Thanks, might we expect to see a version bump?

**Comment by gyscos** [comment]
cursive-core 0.3.4 was released with this fix (and another fix for FixedLayout).

Separately, cursive 0.19.0 was also released to update crossterm to 0.24.0.

(Both changes should be independent: you can use cursive-core 0.3.4 with cursive 0.18.0 or cursive-core 0.3.3 with cursive 0.19.0.)

**Comment by brianc118** [comment]
Hmm I don't see cursive 0.19.0 but I do see cursive-core 0.3.4 on crate.io

**Pull request merged**
