### PR TITLE
[Doc] Improves the documentation about using custom themes

### PR DESCRIPTION
**Pull request by Maximkaaa**
As starting to use the cursive library I've found it challenging to
figure out how to actually use the themes. Only after checking the
source code, and another library actually using this feature, I've
managed to apply it to my project.

This change makes it easier for new commers to use toml themes by
extending the documentationn

### CODE REVIEW

**Comment by gyscos** [comment]
Thanks for the PR!

I do agree that documentation on themes could be much better. The examples help a bit, but the doc itself should provide a bettet understanding.

Note that toml isn't strictly necessary to customize the theme; you should be able to manually update the various colors in the theme's palette.

**Comment by Maximkaaa** [comment]
I've tried to make the description of the theme section more clear. Also added actual hyperlinks inside the theme module docs.

**Comment by vmedea** [comment]
Thanks for writing documentation on this, I've, at times also wanted to customize the colors but haven't got around to it because, as you say, the information to do so is scattered over different places.

**Comment by Maximkaaa** [comment]
@gyscos Do you think this can be merged if you find it helpful for others? Stale PRs make me itchy... :-)

**Comment by gyscos** [comment]
Yes! Sorry - will have some time soon to look at this PR.

**Comment by gyscos** [comment]
Got merged in latest main branch.

**Pull request closed without merging**
