### PR TITLE
Add example of menubar-progressbars combination

### PR DESCRIPTION
**Pull request by matthiasbeyer**
I played around a bit and here is an example for combining a menubar with a progress bar grouping.

Hope such PRs are appreciated as well :smile:

### CODE REVIEW

**Comment by gyscos** [comment]
Nice !
Some comments:

* Instead of wrapping each menubar in a BoxView, you can put one single BoxView around the LinearLayout
* The callback mechanism will soon change, probably using a channel on the Cursive root.
* I'll look into alternative ways to wait for all tasks to complete (semaphore? CondVar?)

**Comment by matthiasbeyer** [comment]
> Instead of wrapping each menubar in a BoxView, you can put one single BoxView around the LinearLayout

Apparently, this does not work. It yields the progress bars beeing of size of 1 cell and you cannot see the progress anymore...

Here's the diff I tried to use:

```patch
diff --git a/examples/menu_progress_combi.rs b/examples/menu_progress_combi.rs
index 0542da6..ccb1405 100644
--- a/examples/menu_progress_combi.rs
+++ b/examples/menu_progress_combi.rs
@@ -61,30 +61,32 @@ fn main() {
            }
        }));
 
-    siv.add_layer(Dialog::new(LinearLayout::vertical()
-            .child(TextView::new("Title").h_align(HAlign::Center))
-            // Box the textview, so it doesn't get too wide.
-            // A 0 height value means it will be unconstrained.
-            .child(BoxView::fixed_width(60, ProgressBar::new()
-                                                .range(0, 100)
-                                                .with_value(value[0].clone())
-                                                .with_callback(cb.clone())))
-            .child(BoxView::fixed_width(60, ProgressBar::new()
-                                                .range(0, 100)
-                                                .with_value(value[1].clone())
-                                                .with_callback(cb.clone())))
-            .child(BoxView::fixed_width(60, ProgressBar::new()
-                                                .range(0, 100)
-                                                .with_value(value[2].clone())
-                                                .with_callback(cb.clone())))
-            .child(BoxView::fixed_width(60, ProgressBar::new()
-                                                .range(0, 100)
-                                                .with_value(value[3].clone())
-                                                .with_callback(cb.clone())))
-            .child(BoxView::fixed_width(60, ProgressBar::new()
-                                                .range(0, 100)
-                                                .with_value(value[4].clone())
-                                                .with_callback(cb.clone())))));
+    siv.add_layer(Dialog::new(
+            BoxView::fixed_width(60,
+                LinearLayout::vertical()
+                    .child(TextView::new("Title").h_align(HAlign::Center))
+                    // Box the textview, so it doesn't get too wide.
+                    // A 0 height value means it will be unconstrained.
+                    .child(ProgressBar::new()
+                            .range(0, 100)
+                            .with_value(value[0].clone())
+                            .with_callback(cb.clone()))
+                    .child(ProgressBar::new()
+                            .range(0, 100)
+                            .with_value(value[1].clone())
+                            .with_callback(cb.clone()))
+                    .child(ProgressBar::new()
+                            .range(0, 100)
+                            .with_value(value[2].clone())
+                            .with_callback(cb.clone()))
+                    .child(ProgressBar::new()
+                            .range(0, 100)
+                            .with_value(value[3].clone())
+                            .with_callback(cb.clone()))
+                    .child(ProgressBar::new()
+                            .range(0, 100)
+                            .with_value(value[4].clone())
+                            .with_callback(cb.clone())))));
 
     siv.add_layer(Dialog::empty()
         .title("Progress bar example")
```

**Comment by matthiasbeyer** [comment]
Just tried with a `FullView` - same result - the progress bar view does not expand automatically.

**Comment by gyscos** [comment]
Might be a bug then - I'll look into what's going on.

**Comment by gyscos** [comment]
* The progress bar width is now fixed.
* The new callback channel on `Cursive` is also live.

**Comment by matthiasbeyer** [comment]
Updated. I do not need the callback infrastructure at all here, I guess. At least it works as expected for me.

**Comment by matthiasbeyer** [comment]
Updated again to remove the unneeded imports.

**Comment by gyscos** [comment]
Having multiple bars is pretty cool, I added it directly in the `progress` example.

Showing interactions between the progress bar and other parts of the UI is another good idea, but I'm not sure the present configuration is ideal to show a real-world-ish usage. Going through the menu-bar for repeatable actions doesn't seem very convenient.
Maybe some buttons under the bars?

As a side note, the `BoxView` API changed a bit; the preferred way is now to call `fixed_width()` on the view directly, without explicitly mentioning the `BoxView`.

**Comment by gyscos** [comment]
1. The example is a bit confusing.
2. Some minor API details have changed, and this example does not compile.

I'll close this PR for now, though improvements to the existing examples are always welcome.

**Pull request closed without merging**
