### PR TITLE
Implement Default for XY

### PR DESCRIPTION
**Pull request by robinkrahl**
This patch implements Default for XY<T> if T implements Default.  This
makes it easier to deal with types like XY<usize>.

### CODE REVIEW

**Comment by gyscos** [comment]
Thanks for the PR!

I think in our case we can just add `Default` to the derived implementations of `XY` (along with `Debug`, `Clone`, ...).

**Comment by robinkrahl** [comment]
You’re right!  I’ve updated the PR.  But why doesn’t the compiler complain about `T` not (necessarily) implementing `Default`?

**Comment by gyscos** [comment]
These derives automatically carry the trait bound to any generic type. It's not always accurate (sometime you don't really depend on the generic type implementing the trait, see [a playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=950288f8f7b3590b116e2bd5c4ff3673)), but in many cases (including ours) it's actually what we want.

**Comment by robinkrahl** [comment]
Wow, that really surprises me.  I’m sure I’ve written something like your example before, expecting that it would *always* implement Default.  Well, it’s always good to learn something new!

**Pull request merged**
